name: Build

permissions:
  contents: write
  actions: read

on:
  push:
    paths:
      - "plugin/**"
      - "proxy/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - ".github/workflows/**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - main
    paths:
      - "plugin/**"
      - "proxy/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle
      - name: Cache Gradle
        uses: actions/cache@v6 # https://github.com/actions/cache/releases
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Test the artifact
        run: |
          test -f plugin/build/libs/mc2p-plugin.jar
          test -f proxy/build/libs/mc2p-proxy.jar
          unzip -l plugin/build/libs/mc2p-plugin.jar | grep -q "plugin.yml"
          unzip -l plugin/build/libs/mc2p-plugin.jar | grep -q "dev/mc2p/lib/mcp/"
          unzip -l proxy/build/libs/mc2p-proxy.jar | grep -q "velocity-plugin.json"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mc2p-dist
          overwrite: true
          path: |
            plugin/build/libs/mc2p-plugin.jar
            proxy/build/libs/mc2p-proxy.jar
          if-no-files-found: error